In [1]:
import torch

In [3]:
import numpy as np

In [4]:
torch.cuda.is_available()

True

In [5]:
!nvidia-smi

Sun Dec 04 21:55:12 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 456.71       Driver Version: 456.71       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 710     WDDM  | 00000000:01:00.0 N/A |                  N/A |
| 40%   37C    P8    N/A /  N/A |    419MiB /  2048MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU  

In [6]:
my_list = [[1,2],[3,4]]

In [7]:
my_list

[[1, 2], [3, 4]]

In [8]:
type(my_list)

list

In [9]:
np.array(my_list)

array([[1, 2],
       [3, 4]])

In [12]:
my_data = torch.tensor(my_list)

In [13]:
my_data

tensor([[1, 2],
        [3, 4]])

In [14]:
type(my_data)

torch.Tensor

In [15]:
my_data.dtype

torch.int64

In [16]:
np_arr = np.random.rand(3,4)

In [17]:
np_arr

array([[0.24872945, 0.9823627 , 0.08313395, 0.24747318],
       [0.53479712, 0.69336222, 0.66491955, 0.22209979],
       [0.59176528, 0.60541628, 0.0595921 , 0.8605061 ]])

In [18]:
torch.from_numpy(np_arr)

tensor([[0.2487, 0.9824, 0.0831, 0.2475],
        [0.5348, 0.6934, 0.6649, 0.2221],
        [0.5918, 0.6054, 0.0596, 0.8605]], dtype=torch.float64)

In [19]:
torch.rand(3,2)

tensor([[0.2149, 0.7971],
        [0.4385, 0.2833],
        [0.1090, 0.8694]])

In [20]:
my_data.device

device(type='cpu')

In [23]:
my_data = my_data.to('cuda')

In [24]:
my_data.device

device(type='cuda', index=0)

In [25]:
my_data.mul(my_data) # why this gives zeros!!!

tensor([[0, 0],
        [0, 0]], device='cuda:0')

In [26]:
my_data

tensor([[1, 2],
        [3, 4]], device='cuda:0')

In [27]:
my_data * my_data # why this gives zeros!!!

tensor([[0, 0],
        [0, 0]], device='cuda:0')

In [28]:
my_data.sum(axis = 1) # why this gives zeros!!!

tensor([0, 0], device='cuda:0')